### ISSUE TITLE
Compact Chest and Simple Storage Network

### ISSUE THREAD

**Issue by Picono435** [deletey/CompactStorage#78]
Cable of Simple Storage Network (link cable) isnt detecting the Compact Chest as a inventory block.

**Comment by choekstr** [comment]
This has been the case since the 1.10 version when I started using this mod (FTB unstable 1.10 days) and environmental tech void miner couldn't push to the chests.  

I came to report the same thing for the 1.12 version and just noticed it with enderIO conduits that don't connect.

Is this intentional, a bug, or an oversight?  

Thanks for the incredible mod and the.very.best.chest.mod in modded minecraft, bar none!

**Comment by choekstr** [comment]
Check out ComPatchedStorage, a fixed version of CompactStorage to fix this issue.
